### ISSUE TITLE
Imitation and flattery

### ISSUE THREAD

**Issue by purcell** [mattjbray/servant-elm#1]
Hey Matt, this is not so much an issue as a "hello", "thanks" and an offer of help, so feel free to immediately close -- I simply prefer to keep open source communication in the open! I'm a buddy of @krisajenkins, and embarrassingly I didn't know about your `servant-elm` when I started working [on my own](https://github.com/purcell/servant-elm) a couple of months ago: searching for prior art turned up nothing at that point.

I quickly started trying to use the new `servant-foreign` library which will be in `servant` 0.5: it removes the need to destructure all the servant type constructions in generation code, instead giving you a value-level tree of ADTs for all the endpoints in an API type. Wanting ultimately to generate decoders/encoders automatically, I bumped up against limitations of `servant-foreign` which I think nobody else has encountered because they haven't been as ambitious as you or I, and I've been trying to get [changes pushed upstream](https://github.com/haskell-servant/servant/pull/351) to remove those limitations.

So firstly, congrats on the excellent work you've done, and I'll likely switch over to using your `servant-elm` over mine. If so, I'll be sure to pitch in and help if I encounter any roadblocks. And secondly, if you have any thoughts on whether it would ultimately help you to use `servant-foreign`, and what might be needed there, I'd be interested to hear it.

Cheers!

**Comment by mattjbray** [comment]
Hi Steve, thanks for the kind words! It's good to know someone else has been working on the same thing.

I'm actually using a few helper functions from `servant-foreign` already, but back when I checked it out I don't think it had the `HasForeignType` goodies.

I've had a look at your haskell-servant/servant#351 PR and with that change I think I could do away with my custom `Request` type and probably the whole `Servant.Elm.Client` module as well.

I'll have a go at integrating that and let you know how I get on. If it works out I'll link to it in your servant PR - it might be useful to have some client code there for context.

**Comment by purcell** [comment]
Great. My guess is that https://github.com/haskell-servant/servant/pull/351 is unlikely to get merged in its current form, but it certainly feels like something like that is necessary. And if it's more obvious to you than me what a neater formulation of that PR would be, that's something I would happily work on.

**Comment by dredozubov** [comment]
I feel like i have to say that it got merge thanks to @purcell, so it have to be properly updated.

**Comment by mattjbray** [comment]
@dredozubov Yes, and it's great that @purcell managed to get it in for the 0.5 release!

I am working on integrating this into `servant-elm` at the moment. There are a couple of issues around handling `NoContent` responses I want to address first, but hopefully there will be something to show after the weekend :)

**Comment by dredozubov** [comment]
@mattjbray great, keep us posted!

**Comment by mattjbray** [comment]
This is now implemented over at #3, please give it a go.  If you have any specific comments about the implementation I'd love to hear them.
