### ISSUE TITLE
Elm code generation problem

### ISSUE THREAD

**Issue by ashishnegi** [mattjbray/servant-elm#10]
Hi
I am trying to generate Elm code from `servant proxy` : [Api.hs] (https://github.com/ashishnegi/sanskell/blob/master/src/Sanskell/Api.hs#L22)

I see that for following [Types.hs] (https://github.com/ashishnegi/sanskell/blob/master/src/Sanskell/Types.hs#L13) :
```
newtype JobId = JobId Int deriving (Eq, Ord, Show, Generic)
```
Elm code generated is :
```
type JobId
  = JobId  : Int
```
which should be
```
type JobId = JobId Int
```
Also code like [decode-code](https://github.com/ashishnegi/sanskell/blob/master/ui/src/Api.elm#L36)
```
decodeJobId : Json.Decode.Decoder JobId
decodeJobId =
<Constructor "JobId" (Selector "" (Field (Primitive "Int")))>
```
is being generated.

Any suggestions on how to solve the problem ?
To reproduce, please clone [sanskell](https://github.com/ashishnegi/sanskell) and run `make ui-setup ui-build`

**Comment by ashishnegi** [comment]
Is there any other way that i can have temporary solution ?
like if i have my own custom `toJSON` for Generic, can `elm-export` take some hint from that ?

**Comment by purcell** [comment]
> Is there any other way that i can have temporary solution ?
> like if i have my own custom toJSON for Generic, can elm-export take some hint from that ?

I don't think so, but that would also be an `elm-export` question.

**Comment by ashishnegi** [comment]
thanks. closing the issue.
