### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [mattjbray/servant-elm#13]
The documentation for the latest version of this package is missing on Hackage. Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by mattjbray** [comment]
Done, thanks for letting me know.

Note to self: I used this script to upload the docs using stack: https://github.com/phadej/binary-orphans/blob/master/hackage-docs.sh
