### ISSUE TITLE
elm-export is now on hackage

### ISSUE THREAD

**Issue by expipiplus1** [mattjbray/servant-elm#14]
Is it possible to update the readme. Is it no longer necessary to build with a custom stack.yaml?

**Comment by mattjbray** [comment]
Actually, it is still necessary - `servant-elm` currently relies on a forked version of `elm-export`. I'm working with krisajenkins to get the features we need into the upstream version - track https://github.com/krisajenkins/elm-export/pull/15 for updates.

I've updated the README here too.

**Comment by mattjbray** [comment]
Everything is now on Hackage :)

**Comment by expipiplus1** [comment]
Great, thanks!
