### ISSUE TITLE
Add support for header parameters

### ISSUE THREAD

**Issue by expipiplus1** [mattjbray/servant-elm#15]
The path `"foo" :> Header "myHeader" Text :> Get '[JSON] Text` doesn't work, `_reqHeaders` is ignored in mkLetRequest.

**Comment by mattjbray** [comment]
Good point, it's been on my to do list for a while. Let me know if this works for you.

**Comment by expipiplus1** [comment]
Excellent, I'll give this a try soon! Thanks.
