### ISSUE TITLE
Creating output directory automatically

### ISSUE THREAD

**Issue by saurabhnanda** [mattjbray/servant-elm#40]
I was trying out `servant-elm` for the first time, and kept running into this issue:

```
Prelude Elm CodeGen> specsToDir specs "/tmp/elm"
Writing: /tmp/elm/AutoGenerated/Api.elm
*** Exception: /tmp/elm/AutoGenerated/Api.elm: openFile: does not exist (No such file or directory)
```

It would be a good idea to use the equivalent of `mkdir -p` to create the output directory.

**Comment by popara** [comment]
You have to have folder structure in place in order for `writeFile` to write-a-file. It doesn't create directories for you.

Hence 

`md /tmp/elm`:)

**Comment by mattjbray** [comment]
Hi @saurabhnanda. Thanks for the issue. `specsToDir` actually comes from https://github.com/krisajenkins/elm-export, so if you think the behaviour could be improved then please file an issue over there.
