### ISSUE TITLE
No instance for Servant.Foreign.Internal.GenerateList

### ISSUE THREAD

**Issue by apatil** [mattjbray/servant-elm#9]
Hi all,

I'm getting

```
    • No instance for (Servant.Foreign.Internal.GenerateList
                         elm-export-0.3.0.0:Elm.Type.ElmTypeExpr
                         (Servant.Foreign.Internal.Foreign
                            elm-export-0.3.0.0:Elm.Type.ElmTypeExpr
                            (Servant.API.BasicAuth.BasicAuth
                               "my-api" BodyType
                             Servant.API.Sub.:> MyApiSpec)))
```

where `BodyType` is a body type for one of the routes in my API, and `MyApiSpec` is part of my Servant API specification.

I'm not seeing where that instance should be created. I created `ElmType` instances for all my things, as you did for the `Book` type in the example, but I don't see any instances for `BooksApi`. I'm on Servant v0.8.1 and the master version of servant-elm.

Thanks!

**Comment by apatil** [comment]
I can reproduce this by changing the books API spec to

`type BooksApi = "books" :> BasicAuth "hello" String :> Get '[JSON] Book`

So it looks like the basic auth part of Servant just hasn't been implemented yet in Servant-Elm. Sorry for the noise.

**Comment by mattjbray** [comment]
No problem.

The instance needs to be added to `servant-foreign` before we can think about how to generate something useful in `servant-elm`.

It seems like there are a couple of issues tracking this: see https://github.com/haskell-servant/servant/issues/463 and https://github.com/haskell-servant/servant/issues/535
